### PR TITLE
Add package.json for npm support

### PR DESCRIPTION
**Pull request by lutangar**
As requested in #37, this add the `package.json` for npm support.
This also fix usage with import/require synthax, otherwise this PR would be useless:
ES6:

```
import porthole from 'porthole';
```

RequireJs:

```
var porthole = require("porthole");
```

**What's left to you:**
Choose a version number that suits you for the package (`1.0.0` as for now) and I'll change it in this PR.

Once merged, you're good to publish this on your own:

```
npm adduser
npm publish
```

> more infos here https://docs.npmjs.com/getting-started/publishing-npm-packages

Cheers.

### CODE REVIEW

**Comment by indraneel** [comment]
@ternarylabs any timeline on this being merged? Would love to use it!

**Comment by ismriv** [comment]
Same here. This is blocking me from using it - don't really want to copy & paste the module :)

**Comment by justinanastos** [comment]
I've been using this in prod for a few weeks with no issues. Can we merge this in or cede control of the repo to the PR creator?

**Comment by justinanastos** [comment]
I've been using this in prod for a few weeks with no issues. Can you merge this in or add @lutangar as a collaborator?

**Comment by justinanastos** [comment]
@ternarylabs Can you please merge this PR?

**Comment by indraneel** [comment]
thanks @georges!

**Comment by georges** [comment]
ah, looks like a (unrelated) porthole package already exists on npmjs

https://www.npmjs.com/package/porthole

any suggestion on how to best handle this?

**Comment by lutangar** [comment]
@georges you might consider using a scope like `@ternarylabs/porthole` see https://docs.npmjs.com/misc/scope 
Or just choose another package name of your liking.

In any case you'll have to change the name used in the `package.json`.

**Comment by jonhallur** [comment]
Is it on npm yet ?

**Pull request merged**
